version: '3.1'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
      # if not found the volume, it will create a new one calles postgres in my local machine root
      # it will conect the volume to the container /var/lib/postgresql/data where the database is stored
